# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

node: docker-1
replicaCount: 1

phpbb:
    repository: wegbereiter/phpbb
    tag: latest
    pullPolicy: Always
    hostPath: /srv/data/wegbereiter/phpbb/phpbb

database:
    repository: bitnami/mariadb
    tag: latest
    pullPolicy: Always
    hostPath: /srv/data/wegbereiter/phpbb/db

nameOverride: ''
fullnameOverride: ''

service:
    type: ClusterIP
    port: 80

ingress:
    enabled: true
    host: "wegbereiter.frozen-bits.de"
    annotations:
        certmanager.k8s.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/tls-acme: '"true"'
