version: '2'
services:
  mariadb:
    image: bitnami/mariadb:latest
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
      MARIADB_DATABASE: bitnami_phpbb
      MARIADB_USER: bn_phpbb
    volumes:
    - /root/data/wegbereiter/forum/db:/bitnami
  phpbb:
    image: wegbereiter/phpbb:latest
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
      MARIADB_HOST: mariadb
      MARIADB_PORT_NUMBER: '3306'
      PHPBB_DATABASE_NAME: bitnami_phpbb
      PHPBB_DATABASE_USER: bn_phpbb
    volumes:
    - /root/data/wegbereiter/forum/phpbb:/bitnami
    labels:
      io.rancher.container.pull_image: always
      kompose.service.type: nodeport
