apiVersion: v1
kind: Service
metadata:
    name: db
    labels:
        app.kubernetes.io/name: db
        helm.sh/chart: {{ include "chart.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
    type: {{ .Values.service.type }}
    clusterIP: None
    ports:
        - port: 42
          targetPort: 42
          protocol: TCP
          name: default
    selector:
        app.kubernetes.io/name: db
        app.kubernetes.io/instance: {{ .Release.Name }}
