apiVersion: v1
kind: Service
metadata:
    name: phpbb
    labels:
        app.kubernetes.io/name: phpbb
        helm.sh/chart: {{ include "chart.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
    type: {{ .Values.service.type }}
    ports:
        - port: {{ .Values.service.port }}
          targetPort: http
          protocol: TCP
          name: http
    selector:
        app.kubernetes.io/name: phpbb
        app.kubernetes.io/instance: {{ .Release.Name }}
